.vscode/settings.json, service/models.py, service/routes.py, tests/factories.py, tests/test_models.py, tests/test_routes.py
- Renamed Model to Customer
- Added new attributes
- Added a test case to create an a customer
- Added a CustomerFactory
=> added customer model

service/routes.py, tests/test_routes.py
- Added create customer endpoint in `routes.py`
- Added test case for create endpoint
=> added customers

service/routes.py, tests/test_routes.py
=> added test cases for list all customers

service/routes.py
=> added index for root url

service/routes.py
fixed the mistakes in the routes file.
=> fixed typos on lines 119 and 138

service/routes.py, tests/test_models.py, tests/test_routes.py
Made following changes:
- added single customer read endpoint to routes.py 
- store location_url when creating customer in routes.py
=> implement customer read endpoint

service/routes.py, tests/test_models.py
=> Add list customers

service/routes.py, tests/test_models.py
fixed index root url and added test for update customer in test_models.py
=> Fixed Root URL

service/models.py, service/routes.py, tests/test_models.py, tests/test_routes.py
- Updated class methods
- Updated deserialize Table schema
- Added Delete Customers endpoint in routes.py
- Added Delete endpoint test cases
- Added serialize test cases
- Added deserialize test cases
=> Added delete route endpoint

tests/test_models.py, tests/test_routes.py
Made the following modifications:
- Added Query test cases in test_model.py
- Added Test Query  in test_routes.py
=> Added test cases for model

service/models.py, service/routes.py, tests/test_models.py, tests/test_routes.py
added test cases to increase coverage
=> Test cases

.devcontainer/devcontainer.json, .github/ISSUE_TEMPLATE/workflows/workflow.yml
=> Add GitHub actions

Dockerfile, k8s/deployment.yaml, k8s/ingress.yaml, k8s/postgres/configmap.yaml, k8s/postgres/pvc.yaml, k8s/postgres/secret.yaml, k8s/postgres/service.yaml, k8s/postgres/statefulset.yaml, k8s/pv.yaml, k8s/service.yaml
=> kubernetes deployment

README.md
Added build status badge to README.md
=> Added Build Status badge

.devcontainer/Dockerfile, Pipfile, Pipfile.lock
- Changed container base image
- Added BDD dependencies to pipfile (behave, selenium, requests, compare3)
- Added directories and files to support BDD tests
=> Set up bdd testing

.gitignore, features/customers.feature
added BDD query function test cases
=> added query customer scenarios

features/customers.feature
=> delete customer UI

.tekton/pipeline.yaml, .tekton/tasks.yaml, .tekton/workspace.yaml, k8s/deployment.yaml, k8s/postgresql/configmap.yaml, k8s/postgresql/pvc.yaml, k8s/postgresql/secret.yaml, k8s/postgresql/service.yaml, k8s/postgresql/statefulset.yaml
- Added temporary postgresql directory to k8s
- Added .tekto directory and yaml files
- Added git clone to pipeline.yaml
=> tekton setup and git clone

.tekton/pipeline.yaml
- added lint to CI/CD pipeline
=> added lint to CI/CD

service/static/js/rest_api.js
prefixed with api for flask-restx
=> prefix api

.tekton/pipeline.yaml, .tekton/tasks.yaml
=> fixed the error for pylint

.tekton/pipeline.yaml
=> testing for ci/cd

k8s/postgresql/configmap.yaml, k8s/postgresql/pvc.yaml, k8s/postgresql/secret.yaml, k8s/postgresql/service.yaml, k8s/postgresql/statefulset.yaml
Reverts CSCI-GA-2820-SP25-003/customers#96
=> Revert "deployed postgres"

.tekton/pipeline.yaml
- added deploy to pipeline.yaml
=> added deploy to CI/CD pipeline
